Remove book-example because it confuses cargo install
cargo install fails with:
error: multiple packages with binaries found: mdbook, mdbook-wordcount